### ISSUE TITLE
Problem in field_temp_glass.csv entries?

### ISSUE THREAD

**Issue by jlabroquere** [pyflowgo/pyflowgo#4]
The file field_temp_glass.csv in resources contains two values for distance 0 :
0 	1110.21468
0 	1118.5401

Is it normal?

**Comment by oryalava** [comment]
Yes, these are field data, and it turns out that two temperatures were obtained at distance=0 (probably due to the use of two geothermoters).

**Comment by jlabroquere** [comment]
Then we need to check what the code is doing for these data at distance=0. I am not sure how the interpolation behaves in this case.

**Comment by jlabroquere** [comment]
This file is indeed not necessary for simulation but just for plotting.

**Comment by oryalava** [comment]
Yes, that is correct ;)
